// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'avatarContainer': string;
  'userInitial': string;
}
export const cssExports: CssExports;
export default cssExports;
