// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'userDescriptionContainer': string;
  'userName': string;
  'userRole': string;
}
export const cssExports: CssExports;
export default cssExports;
