// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'infoSpacing': string;
  'td': string;
}
export const cssExports: CssExports;
export default cssExports;
