name: Deploy to GitHub Page
on: 
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    # Storybook build
    - name: Install
      working-directory: ./frontend-component
      run: |
        yarn install
    - name: Unit-Tests
      working-directory: ./frontend-component
      run: |
        yarn test
    - name: Build-Storybook
      working-directory: ./frontend-component
      run: |
        yarn build-storybook
        pwd
    - name: Deploy_To_GithubPage
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.GIT_PAGE_DEPLOY_STYLE_GUIDE }}
        BRANCH: master # The branch the action should deploy to.
        FOLDER: ./frontend-component/storybook-static # The folder the action should deploy.
        REPOSITORY_NAME: mydatahack/mydatahack.github.io
        TARGET_FOLDER: zeller-design
        CLEAN: true # Automatically remove deleted files from the deploy branch

    # Main App build
    - name: Install
      working-directory: .
      run: |
        yarn install
    - name: Unit-Tests
      working-directory: .
      run: |
        yarn test
    - name: Build-App
      working-directory: .
      run: |
        yarn build
        pwd
    - name: Deploy_To_GithubPage
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.GIT_PAGE_DEPLOY_STYLE_GUIDE }}
        BRANCH: master # The branch the action should deploy to.
        FOLDER: ./dist # The folder the action should deploy.
        REPOSITORY_NAME: mydatahack/mydatahack.github.io
        TARGET_FOLDER: zeller-code-challenge
        CLEAN: true # Automatically remove deleted files from the deploy branch
