name: Test and Build from feature branch
on: 
  push:
    branches-ignore:
      - 'main'
jobs:
  test-and-build-feature-branch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    # Design System build check
    - name: Install
      working-directory: ./frontend-component
      run: |
        yarn install
    - name: Unit-Tests
      working-directory: ./frontend-component
      run: |
        yarn test
    - name: Build-Storybook
      working-directory: ./frontend-component
      run: |
        yarn build-storybook
        pwd
