// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'appHeading': string;
  'hr': string;
  'spinnerContainer': string;
  'withController': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
